import type { Metadata } from "next";

import { montserrat } from "@/components/fonts";
import "@/app/globals.css";

export const metadata: Metadata = {
  title: "TEG - The Entrepreneurial Group E.V. Website",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html>
      <body className={`${montserrat.className} antialiased`}>{children}</body>
    </html>
  );
}
