export const routeSeoEntries = [
  {
    path: "/",
    titleMessageId: "seo.about.title",
    descriptionMessageId: "seo.about.description",
    indexable: true,
    openGraphImagePath: "/shared/heroes/hero-subpage.avif",
    priority: 1,
    changeFrequency: "weekly",
  },
  {
    path: "/about",
    titleMessageId: "seo.about.title",
    descriptionMessageId: "seo.about.description",
    indexable: true,
    openGraphImagePath: "/shared/heroes/hero-subpage.avif",
    priority: 0.8,
    changeFrequency: "monthly",
  },
  {
    path: "/for-students",
    titleMessageId: "seo.students.title",
    descriptionMessageId: "seo.students.description",
    indexable: true,
    openGraphImagePath: "/shared/heroes/hero-students.avif",
    priority: 0.9,
    changeFrequency: "weekly",
  },
  {
    path: "/for-companies",
    titleMessageId: "seo.companies.title",
    descriptionMessageId: "seo.companies.description",
    indexable: true,
    openGraphImagePath: "/shared/heroes/hero-home.avif",
    priority: 0.9,
    changeFrequency: "weekly",
  },
  {
    path: "/events",
    titleMessageId: "seo.events.title",
    descriptionMessageId: "seo.events.description",
    indexable: true,
    openGraphImagePath: "/shared/heroes/hero-subpage.avif",
    priority: 0.8,
    changeFrequency: "weekly",
  },
  {
    path: "/imprint",
    titleMessageId: "seo.imprint.title",
    descriptionMessageId: "seo.imprint.description",
    indexable: true,
    openGraphImagePath: "/shared/heroes/hero-subpage.avif",
    priority: 0.2,
    changeFrequency: "yearly",
  },
  {
    path: "/privacy-policy",
    titleMessageId: "seo.privacy.title",
    descriptionMessageId: "seo.privacy.description",
    indexable: true,
    openGraphImagePath: "/shared/heroes/hero-subpage.avif",
    priority: 0.2,
    changeFrequency: "yearly",
  },
  {
    path: "/request-demo",
    titleMessageId: "seo.requestDemo.title",
    descriptionMessageId: "seo.requestDemo.description",
    indexable: false,
    openGraphImagePath: "/request-demo/hero-bg.jpg",
    priority: 0.3,
    changeFrequency: "monthly",
  },
];
